name: dart_core
description: A sample command-line application.
version: 0.0.1
publish_to: none
repository: https://github.com/qoob23/dart-core

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  collection: ^1.17.0
  directed_graph: ^0.3.7
  meta: ^1.7.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
